version: '2'
services:
  back:
    build: ./back
    restart: on-failure
    ports:
      - "3300:3300"
    volumes:
      - ./back:/usr/app/
      - /usr/app/node_modules
    links:
      - "mysql"
    depends_on:
      - "mysql"
    environment:
      DB_USR: "hypertube"
      DB_PWD: "42"
      DB_HOST: mysql
      DB_NAME: "hypertube"
      MAIL_USR: "contact@toutouparminou.com"
      MAIL_PWD: "Hypertube2020"
      OSB_USR: "Hyp3rtube"
      OSB_PWD: "Hypertube2020"
      JWT_SECRET: "hypertube"
      GITHUB_ID: "f5aee4b642c3f31d7a83"
      GITHUB_SECRET: "ab93a2aaeb83aaca6f122d60d426c00378c1fba0"
      FORTYTWO_ID: "8e001f3beed6c2bc2822bf40de363be697826b51479791faf476545f70cec1f0"
      FORTYTWO_SECRET: "18400a51f3147adf5d8e0a10adc0ac8db4f51cfd3140dc29e83a3ceee4e26b47"
    command: ["./wait-for-it.sh", "mysql:3306","-t", "0", "--", "npm", "start"]
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "toor"
      MYSQL_DATABASE: "hypertube"
      MYSQL_USER: "hypertube"
      MYSQL_PASSWORD: "42"
    ports:
      - "3306:3306"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    restart: always
    ports:
      - 80:80