export const opts = {
  connections: 100,
  uploads: 10,
  path: 'public/movies/',
  verify: true,
  tracker: true,
  trackers: [
    'udp://tracker.openbittorrent.com:80',
    'udp://tracker.ccc.de:80',
    'udp://tracker_proxy:56/announce',
    'udp://tracker_proxy:57/announce',
    'udp://tracker_proxy:58/announce',
    'udp://tracker_proxy:59/announce',
    'udp://tracker_proxy:60/announce',
    'udp://tracker_proxy:61/announce',
    'udp://tracker_proxy:62/announce',
    'udp://tracker_proxy:63/announce',
    'udp://tracker_proxy:64/announce',
    'udp://tracker_proxy:65/announce',
    'udp://tracker_proxy:66/announce',
    'udp://tracker_proxy:67/announce',
    'udp://tracker_proxy:68/announce',
    'https://tracker.bt-hash.com:443/announce',
    'udp://tracker.leechers-paradise.org:6969',
    'https://182.176.139.129:6969/announce',
    'udp://zephir.monocul.us:6969/announce',
    'https://tracker.dutchtracking.com:80/announce',
    'https://grifon.info:80/announce',
    'udp://tracker.kicks-ass.net:80/announce',
    'udp://p4p.arenabg.com:1337/announce',
    'udp://tracker.aletorrenty.pl:2710/announce',
    'udp://tracker.sktorrent.net:6969/announce',
    'udp://tracker.internetwarriors.net:1337/announce',
    'https://tracker.parrotsec.org:443/announce',
    'https://tracker.moxing.party:6969/announce',
    'https://tracker.ipv6tracker.ru:80/announce',
    'https://tracker.fastdownload.xyz:443/announce',
    'udp://open.stealth.si:80/announce',
    'https://gwp2-v19.rinet.ru:80/announce',
    'https://tr.kxmp.cf:80/announce',
    'https://explodie.org:6969/announce',
  ],
}
